### ISSUE TITLE
Feature Request: Add tailwindcss support

### ISSUE THREAD

**Issue by litan1106** [azure-ad-b2c/html-templates#7]
Please add tailwindcss support.

https://tailwindcss.com/docs/installation/play-cdn

**Comment by Eonasdan** [comment]
Hi. I don't know if this will help you or not, but I've been working on a fork to update to [Bootstrap 5](https://github.com/Eonasdan/azure-b2c-html-templates). I managed to unwind the messy CSS from this repo into SCSS and then import and use `@extend` to pull in styles from Bootstrap. Maybe that will give you a head start. If it does work for you, I'd love a PR to help others use tailwinds too.

**Comment by litan1106** [comment]
> Hi. I don't know if this will help you or not, but I've been working on a fork to update to [Bootstrap 5](https://github.com/Eonasdan/azure-b2c-html-templates). I managed to unwind the messy CSS from this repo into SCSS and then import and use `@extend` to pull in styles from Bootstrap. Maybe that will give you a head start. If it does work for you, I'd love a PR to help others use tailwinds too.

awesome. that was a great idea.
